version: '3'

services:
  nuxt:
    container_name: library
    build: docker/Dockerfile
    tty: true
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - "3000:3000"
